### PR TITLE
Default colors should be default and not arbitrary set

### PR DESCRIPTION
**Pull request by sebagomez**
I did a little refactoring and moved some things around.
Default colors were being set arbitrary to back or white while they should be the user's current colors. I also added a .editorconfig file cause I prefer tabs but respect your spaces preferences :)
I also modified the Sample project so it references the Colorify project instead of the Nuget package.

Thank you for your work here... it's literally making my life a lot easier 👍

### CODE REVIEW

**Comment by equiman** [comment]
You're welcome!

@sebagomez always be good to have an extra view point. I'm a little out of time this week but I'll see this pull request soon.

Again thanks... to take the time to see the code and make it better!

**Comment by sebagomez** [comment]
Hey @equiman , do you think you can take a look at this PR.
My project has a reference to the Colorify Nuget pacakge and it's not updated yet. Thanks

**Comment by equiman** [comment]
Yes, tommorrow I have some time ;)

**Comment by equiman** [comment]
I love what you do with abstract class. But I need change default color on my apps.
I hvae an 7x24 issue on production and can't have much time to figured out.

I hope this week can see how to solved it.

**Comment by equiman** [comment]
I tested you PR, but doesn't work good. But I used some parts to change his behavior.

If you want use default console color, not use static methods `Theme.Dark` or `Theme.Light`, instead of create a new instance with `new ThemeDark()` or `new ThemeLight()`;

It's an example using Dark theme colors and Light with default console colors.
```
switch (OS.GetCurrent())
            {
                case "win":
                    _path = new PathsConfigurator(CommandSystem.Win, _fileSystem);
                    _bridgeSystem = BridgeSystem.Bat;
                    _colorify = new Format(Theme.Dark);
                    break;
                case "mac":
                    _path = new PathsConfigurator(CommandSystem.Mac, _fileSystem);
                    _bridgeSystem = BridgeSystem.Bash;
                    _colorify = new Format(new ThemeLight());
                    break;
            }
```

Hope it helps and do what you want. Please, let me know.

**Comment by equiman** [comment]
Available as NuGet package:
https://www.nuget.org/packages/dein.Colorify/2.1.0

Thanks for recommend this changes! I learn a lot combining Interfaces with Abstract classes.

**Comment by equiman** [comment]
@sebagomez this changes works what you expected?

**Comment by sebagomez** [comment]
I'll try them and let you know

**Comment by sebagomez** [comment]
My problem now, I think, is that I moved my project to .NET Core 2.1 and your is still in 2.0, right? I upgraded my local colorify to 2.1 so I'm using that one... let me know, if you upgrade it, it'd be great!

**Comment by equiman** [comment]
Now it's ready for .NET Core 2.1 ... https://www.nuget.org/packages/dein.Colorify/2.2.0

**Comment by sebagomez** [comment]
Cool! I just created the PR for that :)

**Comment by equiman** [comment]
Let me know if this version and changes works as you expected.

**Comment by sebagomez** [comment]
Works like a charm! thanks! 👍

**Pull request closed without merging**
