### PR TITLE
Sometimes WindowWidth returns 0

### PR DESCRIPTION
**Pull request by sebagomez**
When an app is running inside a Docker container `Console.WindowWidth` returns 0, thus the PadRight was throwing an `ArgumentOutOfRangeException`.

Added an innocent check, just in case.

### CODE REVIEW

**Comment by equiman** [comment]
Thanks! 

I'm never run it from Docker, do you have some link or instructions about it?
It will be good make a HardHat Container :D

**Comment by sebagomez** [comment]
I don't have a link, but I can help you out with that.

What does HardHat do? Is it a command line app, right?

**Comment by equiman** [comment]
https://github.com/deinsoftware/hardhat

Yes, Right it's a command line app. It's used for my team to run automated tasks. Something like Jenkins but running Task manually.

**Comment by equiman** [comment]
It will be good have some kind of tutorial or Sample to add Colorify to Docker project and show running. Maybe help other like me :D

**Pull request merged**
